import { Option } from '../types/coreTypes';

export const DHIS2_DATA_ELEMENTS: Option[] = [
    { id: '1', value: 'sT2uMMZvrSJ', label: 'Exempted Cost - Completely Free' },
    { id: '2', value: 'eXUI9zdrFSY', label: 'Exempted Cost - Partially Free' },
    { id: '3', value: 'fuHbV1eiKs0', label: 'Emergency Services - Age 0-9' },
    { id: '4', value: 'qQ8UCWW6YUs', label: 'Emergency Services - Age 10-14' },
    { id: '5', value: 'EtdsmjNmxVZ', label: 'Emergency Services - Age 10-19' },
    { id: '6', value: 'SbdW0pjvph3', label: 'Emergency Services - Age 15-19' },
    { id: '7', value: 'CLYbMAU5lhD', label: 'Emergency Services - Age 20-59' },
    { id: '8', value: 'GaDfMW8NKGd', label: 'Emergency Services - Age 60-69' },
    { id: '9', value: 'HEgvfxOppUY', label: 'Emergency Services - Age 60+' },
    { id: '10', value: 'jXzZ2AFEqgP', label: 'Emergency Services - Age 70+' },
    { id: '11', value: 'sBAeCFmRvOG', label: 'Immunization Clinics - Planned' },
    { id: '12', value: 'w7FmV7f1Rcn', label: 'Immunization Clinics - Conducted' },
    { id: '13', value: 'e0HZBrBDfpg', label: 'Immunization Sessions - Planned' },
    { id: '14', value: 'BF7zguwOCqE', label: 'Immunization Sessions - Conducted' },
    { id: '15', value: 'yUNjmhz0j9s', label: 'Outreach Clinics - Planned' },
    { id: '16', value: 'BG55tDKF0np', label: 'Outreach Clinics - Conducted' },
    { id: '17', value: 'w84aFW1LESM', label: 'Child Vax - BCG' },
    { id: '18', value: 'S4NHzUtxuFr', label: 'Child Vax - DPT-HepB-Hib-1st' },
    { id: '19', value: 'EWloIcvmV6J', label: 'Child Vax - DPT-HepB-Hib-2nd' },
    { id: '20', value: 'BKLqlVqwTX9', label: 'Child Vax - DPT-HepB-Hib-3rd' },
    { id: '21', value: 'F3fBb33oh1c', label: 'Child Vax - PCV-1st' },
    { id: '22', value: 'TkfynUxlyEA', label: 'Child Vax - PCV-2nd' },
    { id: '23', value: 'Pzet2gxoVk4', label: 'Child Vax - PCV-3rd' },
    { id: '24', value: 'j0Bqqi6vw0a', label: 'Child Vax - OPV-1st' },
    { id: '25', value: 'iIBI3R4j7rR', label: 'Child Vax - OPV-2nd' },
    { id: '26', value: 'SZXbOZ7nCcT', label: 'Child Vax - OPV-3rd' },
    { id: '27', value: 'XZZ0Lbe79KT', label: 'Child Vax - Rota-1st' },
    { id: '28', value: 'a6M1cxcfKOC', label: 'Child Vax - Rota-2nd' },
    { id: '29', value: 'W4MXIx0utSp', label: 'Child Vax - FIPV-1st' },
    { id: '30', value: 'HHg41AN9x3a', label: 'Child Vax - FIPV-2nd' },
    { id: '31', value: 'ZVZtO6UfQ85', label: 'Child Vax - JE' },
    { id: '32', value: 'T6HLuCqpOMn', label: 'Maternal TD-2' },
    { id: '33', value: 'q0XkNvBOqZc', label: 'Maternal TD-2+' },
];

export const DHIS2_SOURCE_KEYS: Option[] = [
    { id: 's1', value: 'AGE_0-9_FEMALE', label: 'Age 0-9 Female' },
    { id: 's2', value: 'AGE_0-9_MALE', label: 'Age 0-9 Male' },
    { id: 's3', value: 'AGE_10-14_FEMALE', label: 'Age 10-14 Female' },
    { id: 's4', value: 'AGE_10-14_MALE', label: 'Age 10-14 Male' },
    { id: 's5', value: 'AGE_15-19_FEMALE', label: 'Age 15-19 Female' },
    { id: 's6', value: 'AGE_15-19_MALE', label: 'Age 15-19 Male' },
    { id: 's7', value: 'AGE_20-59_FEMALE', label: 'Age 20-59 Female' },
    { id: 's8', value: 'AGE_20-59_MALE', label: 'Age 20-59 Male' },
    { id: 's9', value: 'AGE_60+_FEMALE', label: 'Age 60+ Female' },
    { id: 's10', value: 'AGE_60+_MALE', label: 'Age 60+ Male' },
    { id: 's11', value: 'CLINIC_PLANNED', label: 'Immunization Clinic Planned' },
    { id: 's12', value: 'CLINIC_CONDUCTED', label: 'Immunization Clinic Conducted' },
    { id: 's13', value: 'VAX_CHILD_BCG', label: 'Child Vax BCG' },
    { id: 's14', value: 'VAX_CHILD_DPT-HEPB-HIB-1ST', label: 'Child Vax DPT-HepB-Hib 1st' },
    { id: 's15', value: 'VAX_CHILD_DPT-HEPB-HIB-2ND', label: 'Child Vax DPT-HepB-Hib 2nd' },
    { id: 's16', value: 'VAX_CHILD_DPT-HEPB-HIB-3RD', label: 'Child Vax DPT-HepB-Hib 3rd' },
    { id: 's17', value: 'VAX_CHILD_PCV-1ST', label: 'Child Vax PCV 1st' },
    { id: 's18', value: 'VAX_CHILD_PCV-2ND', label: 'Child Vax PCV 2nd' },
    { id: 's19', value: 'VAX_CHILD_PCV-3RD', label: 'Child Vax PCV 3rd' },
    { id: 's20', value: 'VAX_CHILD_OPV-1ST', label: 'Child Vax OPV 1st' },
    { id: 's21', value: 'VAX_CHILD_OPV-2ND', label: 'Child Vax OPV 2nd' },
    { id: 's22', value: 'VAX_CHILD_OPV-3RD', label: 'Child Vax OPV 3rd' },
    { id: 's23', value: 'VAX_CHILD_ROTA-1ST', label: 'Child Vax Rota 1st' },
    { id: 's24', value: 'VAX_CHILD_ROTA-2ND', label: 'Child Vax Rota 2nd' },
    { id: 's25', value: 'VAX_CHILD_FIPV-1ST', label: 'Child Vax FIPV 1st' },
    { id: 's26', value: 'VAX_CHILD_FIPV-2ND', label: 'Child Vax FIPV 2nd' },
    { id: 's27', value: 'VAX_CHILD_JE', label: 'Child Vax JE' },
    { id: 's28', value: 'VAX_MATERNAL_TD1', label: 'Maternal TD1' },
    { id: 's29', value: 'VAX_MATERNAL_TD2', label: 'Maternal TD2' },
    { id: 's30', value: 'GESI_KHOP_F_DALIT', label: 'GESI: Full Immunization Female (Dalit)' },
    { id: 's31', value: 'GESI_KHOP_M_DALIT', label: 'GESI: Full Immunization Male (Dalit)' },
    { id: 's32', value: 'GESI_DELIVERY_DALIT', label: 'GESI: Institutional Delivery (Dalit)' },
    { id: 's33', value: 'GESI_GBV_F_DALIT', label: 'GESI: GBV Female (Dalit)' },
    { id: 's34', value: 'FP_CONDOM_NEW_O20', label: 'FP: Condom New User (>=20)' },
    { id: 's35', value: 'FP_PILLS_NEW_O20', label: 'FP: Pills New User (>=20)' },
    { id: 's36', value: 'FP_DEPO_NEW_O20', label: 'FP: Depo New User (>=20)' },
    { id: 's37', value: 'ANC_FIRST_O20', label: 'ANC: First Visit (>=20)' },
    { id: 's38', value: 'DELIVERY_SBA_O20', label: 'Delivery: SBA Conducted (>=20)' },
    { id: 's39', value: 'IMNCI_CHILD_PNEUMONIA', label: 'IMNCI: Child Pneumonia Case' },
];

export const DHIS2_COMBOS: Option[] = [
    { id: 'c1', value: 'kdsirVNKdhm', label: 'default' },
    { id: 'c2', value: 'ye1QuAMRG5Z', label: 'Female' },
    { id: 'c3', value: 'PflKpozpO7b', label: 'Male' },
    { id: 'c4', value: 'A0ezJDD4TfL', label: 'Total Number Tested' },
    { id: 'c5', value: 'wCvNkhhbSbl', label: 'Total Positive Cases' },
];

export const DHIS2_DATASETS: Option[] = [
    { id: 'ds1', value: 'a2JkM9Uvfa2', label: 'HMIS 3.3 - Immunization & Nutrition' },
    { id: 'ds2', value: 'fBTyYLt6u8l', label: 'HMIS 3.4 - Safe Motherhood' },
    { id: 'ds3', value: 'pMTY4vfa2Jk', label: 'HMIS 1.1 - OPD Services' },
    { id: 'ds4', value: 'gEsiReportDataset', label: 'GESI Report Dataset' },
];
